try : 
    a = 10 / 0 
except :
    print("예외상황 에러로 인해 종료합니다.") 
